name: Deploy to Heroku (data-analyzer)

on:
  push:
    branches:
      - main
    paths:
      - "data-analyzer/**"
      - ".github/workflows/data-analyzer.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Add backend remote origin
        run: git remote add heroku-analyzer https://heroku:${{ secrets.HEROKU_API_TOKEN }}@git.heroku.com/${{ secrets.HEROKU_ANALYZER_APP_NAME }}.git
      - name: Deploy backend to Heroku
        run: git push heroku-analyzer `git subtree split --prefix data-analyzer main`:refs/heads/main --force

